version: '2'

services:
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    volumes:
      - drone_delivery_mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: development123
      MYSQL_DATABASE: drone_delivery
volumes:
  drone_delivery_mysql:
