import { Drone } from '../../drone.entity';

export const dronesList: Drone[] = [
  {
    id: 1,
    image: 'http://placeimg.com/640/480',
    name: 'Ms. Clinton Ferry',
    address: '65042 Prohaska Drive',
    battery: 12,
    maxSpeed: 92,
    averageSpeed: 42,
    status: 'success',
  },
  {
    id: 2,
    image: 'http://placeimg.com/640/480',
    name: 'Alan Wilderman',
    address: '460 Favian Garden',
    battery: 20,
    maxSpeed: 67,
    averageSpeed: 17,
    status: 'success',
  },
  {
    id: 3,
    image: 'http://placeimg.com/640/480',
    name: 'Julia Hilpert',
    address: '8202 Wisozk Shores',
    battery: 29,
    maxSpeed: 24,
    averageSpeed: 53,
    status: 'failed',
  },
  {
    id: 4,
    image: 'http://placeimg.com/640/480',
    name: 'Dr. Derek Schaden',
    address: '5768 Waelchi Cliffs',
    battery: 71,
    maxSpeed: 10,
    averageSpeed: 82,
    status: 'failed',
  },
  {
    id: 5,
    image: 'http://placeimg.com/640/480',
    name: 'Ken Ernser II',
    address: '949 Schulist Mills',
    battery: 23,
    maxSpeed: 37,
    averageSpeed: 8,
    status: 'success',
  },
];
